default_agent: strands_weather_agent
agents:
  strands_weather_agent:
    name: strands_weather_agent
    entrypoint: /Users/emota/Projects/building-apps-with-bedrock/Bedrock Agents/strands_weather_agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/emota/Projects/building-apps-with-bedrock/Bedrock Agents
    aws:
      execution_role: arn:aws:iam::058264544288:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-bea28dca66
      execution_role_auto_create: false
      account: 058264544288
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-058264544288-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: strands_weather_agent-m2yEmt2UvZ
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:058264544288:runtime/strands_weather_agent-m2yEmt2UvZ
      agent_session_id: 519d6ae4-ac99-4ea3-9d2b-088d6d554b54
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
